version: "3.7"

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ".:/app"
            - "/app/node_modules"
        ports:
            - 8080:3000
        env_file: .env